- # Билет 11 
- ### Проверка исключений производится с помощью такой конструкции:
    ```
    try {
        // выполняем код, который может выбросить ошибку
        throw new Exception("message");
    } 
    catch (Exception e) {
        // ловим ошибку и выводим подробности
        e.printStackTrace();
    } 
    finally {
        // этот код выполнится независимо от успешности try
        // как "финал" наших действий из try и catch
        System.out.println("блок try/catch законичил своё выполнение");
    }
    ```
- В этом блоке кода заметно слово `throw` ‒ для его применения необходимо, чтобы выбрасываемый объект был наследником `Throwable`
- `Exception` ‒ родительский класс всех исключений. Для него определён конструктор с строкой-сообщением.
- Среди наследников `Exception` существует `RuntimeException`
- Непроверяемые исключения ‒ исключения, которые происходят во время выполнения программы: наследники `RuntimeException`
    - `NullPointerException`
- Проверяемые исключения ‒ исключения, которые выбрасываются другими методами внутри данного метода
    - Их необходимо "проверять"
    - Для того, чтобы указать, что метод выбрасывает исключение сущетсвует слово throws
        - `public static int foo(int a) throws IOException, ... `
    - Без слова `throws` или `try/catch` будет ошибка: Unhandled Exception


- ### Класс ArrayList, LinkedList. Основные реализации. Как работают вставка, удаление, поиск элемента на примере реализаций.
```
import java.util.ArrayList;
import java.util.List;
```
```
List<Integer> intList = new ArrayList<>();

intList.add(2);
intList.addFirst(3);
intList.addLast(1);
intList.add(0, 0); // добавление 0 вперёд
intList.add(2, 15); // добавление 15 третьим

intList.remove(0);
System.out.println("index = " + intList.indexOf(15));
System.out.println(intList.toString());

for (int i = 0; i < intList.size(); ++i)
{
    System.out.println(intList.get(i));
}
```
