- # Билет 11 
- Проверка исключений производится с помощью такой конструкции:
    ```
    try {
        // выполняем код, который может выбросить ошибку
        throw new Exception("message");
    } 
    catch (Exception e) {
        // ловим ошибку и выводим подробности
        e.printStackTrace();
    } 
    finally {
        // этот код выполнится независимо от успешности try
        // как "финал" наших действий из try и catch
        System.out.println("блок try/catch законичил своё выполнение");
    }
    ```
- В этом блоке кода заметно слово `throw` ‒ для его применения необходимо, чтобы выбрасываемый объект был наследником `Throwable`
- `Exception` ‒ родительский класс всех исключений. Для него определён конструктор с строкой-сообщением.
- Среди наследников `Exception` существует `RuntimeException`
- Непроверяемые исключения ‒ исключения, которые происходят во время выполнения программы: наследники `RuntimeException`
    - `NullPointerException`
- Проверяемые исключения ‒ исключения, которые выбрасываются другими методами внутри данного метода
    - Их необходимо "проверять"
    - Для того, чтобы указать, что метод выбрасывает исключение сущетсвует слово throws
        - `public static int foo(int a) throws IOException, ... `
    - Без слова `throws` или `try/catch` будет ошибка: Unhandled Exception
- 
